# In this, We are going to Handle the Imbalanced Datasets

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import warnings

warnings. simplefilter(action = "ignore", category = Warning)

In [2]:
data = pd.read_csv("F:/files/310_23498_compressed_creditcard.csv/creditcard.csv")

In [3]:
data.head(5)

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
data['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

#It is highly imbalanced

# First Find the model accuracy by keeping the variable as it is

In [5]:
df = data.copy()

In [6]:
X = df.drop(columns = ['Class'])
Y = df[['Class']]

In [7]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y, train_size = 0.7)

In [8]:
Y_train

Class
132322      0
172632      0
382         0
92962       0
270686      0
...       ...
160452      0
199094      0
189481      0
161574      0
208720      0

[199364 rows x 1 columns]

In [9]:
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score,confusion_matrix, classification_report

In [16]:
classifier = RandomForestClassifier()

classifier.fit(X_train,Y_train)

RandomForestClassifier()

In [18]:
Y_pred = classifier.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test, Y_pred))

[[85302     4]
 [   31   106]]
0.9995903701883126
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85306
           1       0.96      0.77      0.86       137

    accuracy                           1.00     85443
   macro avg       0.98      0.89      0.93     85443
weighted avg       1.00      1.00      1.00     85443



It looks good. we will see what will happend after sampling techniques.

# Under Sampling

In [10]:
from imblearn.under_sampling import NearMiss

In [11]:
ns = NearMiss(0.7)

In [12]:
X_train_ns, Y_train_ns = ns.fit_sample(X_train,Y_train)

In [13]:
print(Y_train.value_counts())

Class
0        199009
1           355
dtype: int64


In [14]:
print(Y_train_ns.value_counts())

Class
0        507
1        355
dtype: int64


### NearMiss of 0.7 explains that 512 * 0.7 = 361

## Performing randomforest to find the result

### I am going to sample the test data also

In [19]:
classifier = RandomForestClassifier()
classifier.fit(X_train_ns,Y_train_ns)

RandomForestClassifier()

In [22]:
X_test_ns, Y_test_ns = ns.fit_sample(X_test,Y_test)

In [25]:
Y_pred = classifier.predict(X_test_ns)
print(confusion_matrix(Y_test_ns, Y_pred))
print(accuracy_score(Y_test_ns,Y_pred))
print(classification_report(Y_test_ns,Y_pred))

[[168  27]
 [ 11 126]]
0.8855421686746988
              precision    recall  f1-score   support

           0       0.94      0.86      0.90       195
           1       0.82      0.92      0.87       137

    accuracy                           0.89       332
   macro avg       0.88      0.89      0.88       332
weighted avg       0.89      0.89      0.89       332



its also looks good if we under sampling the test data.

But we loose more informations and data's

It is good only if we have the less number of the datasets.

let see, what happend if we are not implementing the under sampling to the test data.

## I need to find the result without sampling the test data.

In [26]:
Y_pred = classifier.predict(X_test)

In [28]:
print(confusion_matrix(Y_test, Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[63182 22124]
 [   11   126]]
0.7409384033800311
              precision    recall  f1-score   support

           0       1.00      0.74      0.85     85306
           1       0.01      0.92      0.01       137

    accuracy                           0.74     85443
   macro avg       0.50      0.83      0.43     85443
weighted avg       1.00      0.74      0.85     85443



It looks very bad

Most of the higher data cases, under sampling doesnt work

# Over Sampling

In [30]:
from imblearn.over_sampling import RandomOverSampler

In [33]:
os = RandomOverSampler()

In [35]:
X_train_os, Y_train_os = os.fit_sample(X_train,Y_train)

In [36]:
print(Y_train.value_counts())
print(Y_train_os.value_counts())

Class
0        199009
1           355
dtype: int64
Class
1        199009
0        199009
dtype: int64


#### without giving any sampling strategy, it equalizes the variable

In [38]:
classifier.fit(X_train_os,Y_train_os)

RandomForestClassifier()

In [39]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(Y_test,y_pred))
print(accuracy_score(Y_test,y_pred))
print(classification_report(Y_test,y_pred))

[[85302     4]
 [   32   105]]
0.9995786664794073
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85306
           1       0.96      0.77      0.85       137

    accuracy                           1.00     85443
   macro avg       0.98      0.88      0.93     85443
weighted avg       1.00      1.00      1.00     85443



In [42]:
#By giving sampling strategy of 0.5
os = RandomOverSampler(0.5)
X_train_os, Y_train_os = os.fit_sample(X_train, Y_train)

#### After the sampling strategy of giving 0.5, 

In [43]:
classifier.fit(X_train_os,Y_train_os)

RandomForestClassifier()

In [44]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(Y_test,y_pred))
print(accuracy_score(Y_test,y_pred))
print(classification_report(Y_test,y_pred))

[[85301     5]
 [   31   106]]
0.9995786664794073
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85306
           1       0.95      0.77      0.85       137

    accuracy                           1.00     85443
   macro avg       0.98      0.89      0.93     85443
weighted avg       1.00      1.00      1.00     85443



### If we over sampling the test data also, 

In [45]:
X_test_os,Y_test_os = os.fit_sample(X_test, Y_test)

In [46]:
y_pred = classifier.predict(X_test_os)
print(confusion_matrix(Y_test_os,y_pred))
print(accuracy_score(Y_test_os,y_pred))
print(classification_report(Y_test_os,y_pred))

[[85301     5]
 [ 9720 32933]]
0.9239990934596238
              precision    recall  f1-score   support

           0       0.90      1.00      0.95     85306
           1       1.00      0.77      0.87     42653

    accuracy                           0.92    127959
   macro avg       0.95      0.89      0.91    127959
weighted avg       0.93      0.92      0.92    127959



Best sampling technique for the particular dataset is only based on the results. 

Trail and error method.

# Appling SMOTE method

In [48]:
from imblearn.combine import SMOTETomek

In [50]:
sm = SMOTETomek() #first try without giving the sampling strategy

In [51]:
X_train_sm, Y_train_sm = sm.fit_sample(X_train,Y_train)

In [52]:
print(Y_train.value_counts())
print(Y_train_sm.value_counts())

Class
0        199009
1           355
dtype: int64
Class
1        198443
0        198443
dtype: int64


In [53]:
classifier = RandomForestClassifier()
classifier.fit(X_train_sm,Y_train_sm)

RandomForestClassifier()

In [54]:
y_pred = classifier.predict(X_test)

print(confusion_matrix(Y_test,y_pred))
print(accuracy_score(Y_test,y_pred))
print(classification_report(Y_test,y_pred))

[[85292    14]
 [   25   112]]
0.9995435553526912
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85306
           1       0.89      0.82      0.85       137

    accuracy                           1.00     85443
   macro avg       0.94      0.91      0.93     85443
weighted avg       1.00      1.00      1.00     85443



It gives much better for this dataset.


In [55]:
#trying with giving the sampling strategy

sm = SMOTETomek(0.5)

In [57]:
X_train_sm,Y_train_sm = sm.fit_sample(X_train,Y_train)

In [58]:
print(Y_train.value_counts())
print(Y_train_sm.value_counts())

Class
0        199009
1           355
dtype: int64
Class
0        198209
1         98704
dtype: int64


In [59]:
classifier = RandomForestClassifier()
classifier.fit(X_train_sm,Y_train_sm)

RandomForestClassifier()

In [60]:
y_pred = classifier.predict(X_test)

print(confusion_matrix(Y_test,y_pred))
print(accuracy_score(Y_test,y_pred))
print(classification_report(Y_test,y_pred))

[[85289    17]
 [   25   112]]
0.9995084442259752
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85306
           1       0.87      0.82      0.84       137

    accuracy                           1.00     85443
   macro avg       0.93      0.91      0.92     85443
weighted avg       1.00      1.00      1.00     85443



# Ensembled Techniques

In [61]:
from imblearn.ensemble import EasyEnsembleClassifier

In [62]:
easy = EasyEnsembleClassifier()

In [65]:
easy.fit(X_train,Y_train)

EasyEnsembleClassifier()

In [67]:
y_pred = easy.predict(X_test)

print(confusion_matrix(Y_test,y_pred))
print(accuracy_score(Y_test,y_pred))
print(classification_report(Y_test,y_pred))

[[82773  2533]
 [   13   124]]
0.9702023571269736
              precision    recall  f1-score   support

           0       1.00      0.97      0.98     85306
           1       0.05      0.91      0.09       137

    accuracy                           0.97     85443
   macro avg       0.52      0.94      0.54     85443
weighted avg       1.00      0.97      0.98     85443



### By changing the parameters in the Regression models are also sometimes useful

### (i.e) Cross Validation with Kfold & Tuning the Hyper parameters with the model In LOR and also in LR